### ISSUE TITLE
Edit README.MD to add the new blueprint avatar

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster-quarkus#109]
When this PR has been merged.
https://github.com/jhipster/jhipster-artwork/pull/14

**Comment by nshaw** [comment]
@avdev4j , was this issue meant for generator-jhipster-quarkus or the jhipster docs, e.g. under https://github.com/jhipster/jhipster.github.io/tree/main/images/logo?

**Comment by avdev4j** [comment]
sorry @nshaw
I thought about the Quarkus Readme, the avatar is already in the JHipster artwork repository. 
We dit not move those new members to the website but maybe we could think about that.
