### ISSUE TITLE
Fix broken admin pages

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster-quarkus#153]
Following this ticket https://github.com/jhipster/generator-jhipster-quarkus/issues/145

I've figured out the following admin pages are not working properly:
- [x] logs https://github.com/jhipster/generator-jhipster-quarkus/pull/161
- [x] config https://github.com/jhipster/generator-jhipster-quarkus/pull/158
- [x] audit
- [x] database https://github.com/jhipster/generator-jhipster-quarkus/pull/162
- [X] metrics https://github.com/jhipster/generator-jhipster-quarkus/pull/147 & https://github.com/jhipster/generator-jhipster-quarkus/pull/159

## logs
~This feature is related to Spring boot actuator https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html. 
We should not implement that since we don't have any solution out of the box for Quarkus.
**Action**: Open a ticket to remove logs feature in frontend (code and tests).~

## config
~This feature is related to Spring boot actuator https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html. 
We should not implement that since we don't have any solution out of the box for Quarkus.
**Action**: Open a ticket to remove config feature in frontend (code and tests).~
**Action**:  expose configurations through a specific endpoint, sample app https://github.com/avdev4j/sample-quarkus-configuration

## Audit
~Audit is removed in the JHipster v7. I suggest not change anything on our side since we'll probably release the v1 with the v7 of JHipster. This means audits will be totally removed from the frontend.
**Action**:  Open a pr to clean the backend code from Audit commented artifacts~
Finally nothing to od here because the audit element in the entities (user) are not related the Audit page.

## Database
The h2 console is not available on the Quarkus admin pages. Let's try to enable it with this solution:
https://stackoverflow.com/questions/61853691/how-to-set-h2-database-console-url-in-the-quarkus-application
**Action**:  Open a pr to add to h2 console

## Misc
Override protractor tests to remove not relevant tests for Quarkus (logs, audit, config...)

I think we should focus on Quarkus features than try to reproduce Spring boot one even if it means less features on the frontend part.

This should be done for the v1, if we want to have a production-ready app.

WDYT?
cc @danielpetisme @joewhite101 @mraible

**Comment by mraible** [comment]
Sounds good to me!

**Comment by danielpetisme** [comment]
The original issue had a bounty so I transfer it to  the current one.

**Comment by avdev4j** [comment]
I'm not sure about the props page. Maybe we can implement it easily by exposing the loaded conf through the dedicated endpoint

**Comment by avdev4j** [comment]
I have added metrics too

**Comment by avdev4j** [comment]
I have added the possibilty to expose configurations

**Comment by avdev4j** [comment]
cc @pascalgrimaud 
Bounty claimed here
https://opencollective.com/generator-jhipster/expenses/32055

**Comment by pascalgrimaud** [comment]
@avdev4j : approved
