### ISSUE TITLE
Provide a `/management/threadump` endpoint

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster-quarkus#157]
**Is your feature request related to a problem? Please describe.**
Relates to #147 
Quarkus does not provide an easy way to make a thread dump as Spring does.
As consequence, the metrics page is not exactly the same between the Quarkus and Spring JHipster implementation which forces the blueprint to have custom client metrics pages (see #147).

**Describe the solution you'd like**
The expected behavior is to generate the implementation of the `/management/threadump` endpoint to reuse the upstream JHipster pages

**Describe alternatives you've considered**

**Additional context**

**Comment by avdev4j** [comment]
closed by https://github.com/jhipster/generator-jhipster-quarkus/pull/159
