### ISSUE TITLE
Connect Error due to MYSQL_USER not being root in DEV Mode (mariadb)

### ISSUE THREAD

**Issue by dminkovski** [jhipster/generator-jhipster-quarkus#170]
**Describe the bug**
JDL Setup

> 
> application {
> config {
> baseName gateway,
> applicationType gateway,
> packageName com.test.application,
> authenticationType oauth2,
> prodDatabaseType mariadb,
> databaseType sql,
> devDatabaseType mariadb,
> serverPort 8080,
> clientFramework react,
> blueprint quarkus,
> buildTool maven,
> languages [en, de],
> nativeLanguage en,
> serviceDiscoveryType eureka,
> skipUserManagement true,
> }
> }

When you setup the quarkus application and use mariadb you get a connect error because the default user of the properties is the application name whereas the config yml uses root as the username.
This can easily be fixed by changing the username to root.

`%dev.quarkus.datasource.username=root`

**To Reproduce**

1. RUN jhipster-quarkus jdl .\jhipster-jdl.jdl (authenticationType oauth2)
2. RUN jhipster-quarkus docker-compose
3. Go to src/main/docker and RUN docker-compose -f .\mariadb.yml up
4. Go to gateway folder and RUN .\mvnw
5. Error in connecting to the database

**Expected behavior**
Connection to the datatabase works and the application starts up.

**Screenshots**
![database_error](https://user-images.githubusercontent.com/1609264/108177190-32706780-7103-11eb-91dc-f6f8a45ac0e1.png)

**Desktop:**

-   OS: Windows 10

**Comment by dminkovski** [comment]
This would be fixed in the PR : Added new keycloak realm config jsons for quarkus authorization bug #169

**Comment by avdev4j** [comment]
is it related to it ?

https://github.com/jhipster/generator-jhipster/pull/14477#issuecomment-808906522
