### ISSUE TITLE
Add a CI job that tests the native build

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#175]
**Is your feature request related to a problem? Please describe.**

Add a GitHub Action (or other CI mechanism) that generates an app and packages it with `-Pnative`. Compilation should be enough, but running a simple test to prove it starts would probably be good too.

For GitHub actions with GraalVM, you might check out the Okta CLI's [graalvm.yml](https://github.com/okta/okta-cli/blob/master/.github/workflows/graalvm.yml). 

**Describe the solution you'd like**

As part of PRs (or a nightly process), native builds are confirmed to work.

**Describe alternatives you've considered**

Manually testing.

**Additional context**

This would help identify issues sooner.

**Comment by avdev4j** [comment]
Hi there,
few things:

We can't add a native build with Mongo because of this issue: https://github.com/jhipster/generator-jhipster-quarkus/issues/179

imperative-ngx-jwt-maven-mysql-redis always reached the timeout but everything is fine in my own environment.

**Comment by avdev4j** [comment]
We also need to improve the native tests that we generate to make the builds more complete. https://github.com/jhipster/generator-jhipster-quarkus/issues/49

**Comment by avdev4j** [comment]
claimed here https://opencollective.com/generator-jhipster/expenses/55573

**Comment by pascalgrimaud** [comment]
@avdev4j : approved
