### ISSUE TITLE
Unable to find H2 JDBC driver #8

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster-quarkus#193]
See https://github.com/jhipster/jhipster-sample-app-quarkus/issues/8

**Comment by agoncal** [comment]
@danielpetisme in the pom.xml` you have two dependencies: the H2 for test purposes:

```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-test-h2</artifactId>
    <scope>test</scope>
</dependency>
```

But then you have H2 in the `dev` profile: 

```
<profile>
    <id>dev</id>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
    <properties>
        <!-- default Quarkus profiles -->
        <quarkus.profile>dev</quarkus.profile>
    </properties>
    
    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-h2</artifactId>
        </dependency>
    </dependencies>
</profile>
```

That means that, to make the application work, you cannot use `mvn quarkus:dev` but instead `mvn -Pdev quarkus:dev`. This is not very intuitive as Quarkus does not do that out of the bow.

**Comment by agoncal** [comment]
I've also spotted a few differences. Today the H2 JDBC URL is 

```
%test.quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:test
```

So when the app starts, we have:

```
[INFO] H2 database started in TCP server mode; server status: TCP server running at tcp://localhost:9092 (only local connections)
```

If you read the [H2 documentation](http://www.h2database.com/html/features.html#in_memory_databases), you find that: "To access an in-memory database from another process or from another computer, you need to start a TCP server in the same process as the in-memory database was created.". 

I don't know if this is needed or this has a performance overhead. But the JDBC URL could maybe just be

```
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
```

**Comment by agoncal** [comment]
Also,  `TestResources.java` can be avoided if the dependency:

```
       <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-test-h2</artifactId>
            <scope>test</scope>
        </dependency>
```

is changed to:

```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-h2</artifactId>
            <scope>test</scope>
        </dependency>
```

**Comment by agoncal** [comment]
See https://github.com/jhipster/generator-jhipster-quarkus/pull/206/commits/bda7de4c19147a729fc5c49429e3cb6c18ae1267
