### ISSUE TITLE
Migrating Mongo to DevServices

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster-quarkus#213]
**Describe the bug**

Today the generated application that use MongoDB as a primary database, use Mongock for testing. We should use DevServices instead. But some migration is needed

**Migrating Configuration**

Today the Mongo configuration is as follow:

```
jhi.mongodb.port=27017
%test.jhi.mongodb.port=37017
jhi.mongodb.host=localhost
%prod.jhi.mongodb.host=localhost
quarkus.mongodb.connection-string=mongodb://${jhi.mongodb.host}:${jhi.mongodb.port}
quarkus.mongodb.database=dummy
```

The end result should look like:

```
%test.quarkus.mongodb.devservices.image-name=mongo:4.2.7
%test.quarkus.mongodb.devservices.port=27017
quarkus.mongodb.database=dummy
%prod.quarkus.mongodb.connection-string=mongodb://localhost:27017
```

**Migrating Test Configuration**

`MongoDbTestResource`.

**Pom.xml**

We can get all the dependencies on MongoDB and Mongock and only leave `quarkus-mongodb-panache`

**Comment by agoncal** [comment]
There is an authentication problem. All the tests in `UserResourceTest` fail with 

```
status=401, title="Unauthorized", detail="HTTP 401 Unauthorized"

java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <401>.
```

**Comment by agoncal** [comment]
Here are some differences between the Mongo and SQL setup and code:

* `InitialSetupMigration.java`: Creates the initial database setup
* `MongockConfiguration.java`
* `reflect-config-mongo.json`
* `MongoDbTestResource.java`

**Comment by mraible** [comment]
Added a bug bounty to increase motivation.

**Comment by mraible** [comment]
@agoncal Are you interested in continuing this work? I'd like to see this blueprint succeed and I'm willing to help make it happen.

**Comment by agoncal** [comment]
@mraible  unfortunatelly I won't be able to work on that, too much on my plate :o(
