### ISSUE TITLE
v1.1.1 release is missing on GitHub

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#221]
v1.1.1 is available on [npm](https://www.npmjs.com/package/generator-jhipster-quarkus). However, it doesn't show as the lastest [release on GitHub](https://github.com/jhipster/generator-jhipster-quarkus/releases).

**Comment by avdev4j** [comment]
Done!

https://github.com/jhipster/generator-jhipster-quarkus/releases

**Comment by avdev4j** [comment]
(2.0.0 Beta 1 too)
