### ISSUE TITLE
Support latest version of Quarkus

### ISSUE THREAD

**Issue by aminnasiri** [jhipster/generator-jhipster-quarkus#228]
**Is your feature request related to a problem? Please describe.**
Yes, I need to run JHipster by the latest version of Quarkus which has lots of features.

**Describe the solution you'd like**
I worked a bit on this template of the project and it seems, there are a few things to be able to use Quarkus 2.* e.g.
Eclipse ConfigProperty and ConfigMapping

**Describe alternatives you've considered**
As a JHispter developer, I would like to use the latest version of Quarkus instead of version 1.* of this framework.

**Additional context**
there is not any additional.

**Comment by mraible** [comment]
I agree this would be good. I believe this support is in the `main` branch. I added a bounty to encourage a release. 🤓

**Comment by skkrishn1** [comment]
Matt 
I can support this project , I'm having 15 yrs experience in Java platform, let me know 

Thanks
Suresh K

**Comment by mraible** [comment]
@skkrishn1 Please see our [bug bounty docs](https://www.jhipster.tech/bug-bounties/) for information on how we pay contributors.

**Comment by skkrishn1** [comment]
Thanks Matt , sorry for the late reply.could you please help me out in
setting up the environment ? I will try to fix the bugs.


Thanks
Suresh K

**Comment by mraible** [comment]
@skkrishn1 There are [instructions in this project's README](https://github.com/jhipster/generator-jhipster-quarkus#running-local-blueprint-version-for-development).

**Comment by skkrishn1** [comment]
Thanks Matt , will see the instruction, and  I accepted the meetup invite
will see you on Sep 29 SF JUG 👍.

Thanks
SK

**Comment by mraible** [comment]
Is anyone able to work on this? If not, I can dedicate some time this week.

**Comment by VeitWeber** [comment]
@mraible Maybe I can support you. Just give me a sign.

**Comment by mraible** [comment]
@VeitWeber Take it away! I can help if you have questions or run into issues.

**Comment by VeitWeber** [comment]
@mraible Nah, wasn't my intention. I'm experienced with JEE / Quarkus and would love to deep dive into JHipster...but miles to go ;).

**Comment by vishal423** [comment]
I have started on maven part to bump dependencies to latest. I will soon raise a draft PR.
