### ISSUE TITLE
Missing package.json when using --skip-client

### ISSUE THREAD

**Issue by wanghengxn** [jhipster/generator-jhipster-quarkus#233]
**Describe the bug**
Using option '--skip-client', can't find the package.json file in generated code.

**To Reproduce**

1.  jhipster --blueprints quarkus --skip-client

**Expected behavior**
generate a package.json

**Screenshots**
```
Installing generator-jhipster@6.10.5 locally using npm
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/whx/myWorkspace/quarkusDemo/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/whx/myWorkspace/quarkusDemo/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/whx/.npm/_logs/2021-11-03T01_25_16_456Z-debug.log
```

**Desktop (please complete the following information):**

-   OS: MacOS
-   Version jhpster version 6.10.5

**Comment by vishal423** [comment]
In the latest version, I can see the `package.json`, however, a few dependencies are missing causing git commit hooks to behave weirdly.

**Comment by emilpaw** [comment]
I couldn't reproduce this with version 3.1.0.

**Comment by mraible** [comment]
Closing due to lack of response.
