### ISSUE TITLE
Svelte Frontend support

### ISSUE THREAD

**Issue by eucariop** [jhipster/generator-jhipster-quarkus#237]
Some ideas Svelte module for JHipster Quarkus compatible.
How does the implementation work together or separately.
There is reference Svelte for Spring: https://github.com/jhipster/generator-jhipster-svelte.

I await your comments, greetings

**Comment by mraible** [comment]
You should be able to install two blueprints at a time. I haven't tried it myself, but please report on your progress if you try.

**Comment by mraible** [comment]
Closing due to lack of response.
