### ISSUE TITLE
Upgrade to JHipster 7.9.3

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#245]
**Is your feature request related to a problem? Please describe.**

Upgrade to the latest release of JHipster. This might require refactoring to use the latest blueprint architecture.

**Comment by mshima** [comment]
It’s already using v7 at main, I don’t think it needs another refactoring right now, I will take a look.

**Comment by vishal423** [comment]
I started looking into the `quarkus` and will see if I can contribute. Meantime, I believe this upgrade should be independent of quarkus and can be done independently. I can take a look if not already been handled.

**Comment by mraible** [comment]
Please do @vishal423. I'll have time in November, but that's a ways off.
