### ISSUE TITLE
Release 2.0 version of this blueprint

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#256]
Since this blueprint is up-to-date, we should do a release. If there's any other issues or PRs that you think should be included, please add a comment.

**Comment by vishal423** [comment]
I think we should address #249 and issues identified as part of #225

**Comment by vishal423** [comment]
Now that most of the flows are working end-to-end, do you want to proceed with another beta?

**Comment by mraible** [comment]
Yes, and a proper GA release shortly after if there are no bugs filed!

**Comment by mraible** [comment]
Sorry for my lack of attention to this project. I had a nice holiday break and it's been a struggle to catch back up. I'm adding a bug bounty to this issue. 

@vishal423 What issues do you think we should fix before a release?

**Comment by vishal423** [comment]
I would like to close #273 and if possible, make some progress on #258 and #49 before next release.

**Comment by mraible** [comment]
@vishal423 Sounds good! Please let me know if you'd like help. I can also assign bug bounties to the first two issues if you'd like. The 3rd issue already has a bounty assigned.

**Comment by vishal423** [comment]
@mraible, I will let you know if #258 requires bug bounty (in case it involves more effort)

**Comment by vishal423** [comment]
@mraible, Let's not wait for #258 as it may take a little more time. With #273 and #49 addressed, I think we can do a new release. It should also fix issues reported by users with old releases and make the published version a usable one.

Further improvements can be done as part of the next release.

**Comment by mraible** [comment]
Sounds good to me!

**Comment by vishal423** [comment]
I will try to publish new release by tomorrow or day after

**Comment by mraible** [comment]
That's awesome @vishal423! Thanks for all your work on this blueprint.

**Comment by vishal423** [comment]
@pascalgrimaud, can you please check if sonar project exists for `https://github.com/jhipster/jhipster-sample-app-quarkus` repository? It would be helpful if you can create one, if not present.

**Comment by pascalgrimaud** [comment]
@vishal423 : as far as I remember, it doesn't exist yet. Sonar is a little bit complex and I don't have computer until monday so can't do it with phone. Unless another lead could do it, I'll try to not forget the next week :-)

**Comment by vishal423** [comment]
no hurry. take your time @pascalgrimaud

**Comment by vishal423** [comment]
Closed by https://github.com/jhipster/generator-jhipster-quarkus/pull/283

**Comment by pascalgrimaud** [comment]
just checked this ticket https://github.com/jhipster/generator-jhipster-quarkus/issues/68

Everything was already done in the past, but was never used :-D

**Comment by pascalgrimaud** [comment]
The project was created again:
- https://sonarcloud.io/project/configuration?id=jhipster_jhipster-sample-app-quarkus
- the SONAR_TOKEN was updated at https://github.com/jhipster/jhipster-sample-app-quarkus/settings/secrets/actions

**Comment by pascalgrimaud** [comment]
@vishal423 : do you want me to update the SONAR_TOKEN for https://sonarcloud.io/project/overview?id=jhipster_jhipster-quarkus ? and link to THIS project instead ?

**Comment by vishal423** [comment]
Thanks @pascalgrimaud, I will take a look on further integration. For `quarkus-jhipster` blueprint project, the sonar integration seems to work fine, so no further changes required.
