### ISSUE TITLE
Upgrade Mongock dependency to v5.1.0

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-quarkus#279]
**Is your feature request related to a problem? Please describe.**
`v5.1.0` contains some breaking changes. Refer [migration guide](https://docs.mongock.io/v5/migration/index.html)

**Describe the solution you'd like**
Should support the latest stable release.

**Describe alternatives you've considered**
N/A

**Additional context**
Refer https://github.com/jhipster/generator-jhipster-quarkus/pull/247/commits/3cf3bd5273492ad5ae43f72466cf2129012e16e7

**Comment by vishal423** [comment]
@mraible, Since you already worked on this part before, do you want to take it up?

**Comment by mraible** [comment]
I'm can take a look on Monday. Steps to reproduce would be awesome.

**Comment by vishal423** [comment]
@mraible, Sorry for the late reply. Lately I was bit occupied and could not spend much time over here. This ticket is to upgrade the dependencies and adjust code. In the linked commit, I see you had already tried/explored most of the changes. Let me know if you want to continue to take it to completion.

**Comment by vishal423** [comment]
I was able to make some progress and resolve most of the issues. However, native tests do yet work and fail due to a similar error as in the previous version.

If we are fine with this limitation, then, I can try templatizing these changes and raise PR in the next few days.

**Comment by mraible** [comment]
Sounds good!

**Comment by mraible** [comment]
Adding a bug bounty.

**Comment by vishal423** [comment]
@kamilkrzywanski , If I recall correctly, there was some issue with native tests after upgrade. Does that works now?

**Comment by kamilkrzywanski** [comment]
Fixed and tested according to official documentation: https://github.com/mongock/graalvm-example
and added required graalvm library jboss-vfs
PR:  https://github.com/jhipster/generator-jhipster-quarkus/pull/426

**Comment by kamilkrzywanski** [comment]
@mraible here is also native fix commit #426
