### ISSUE TITLE
Release v3.0 with Quarkus 3 support

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#294]
Please edit this description and add tasks as appropriate.

**Comment by mraible** [comment]
I think we should upgrade to JHipster 8 before we release v3.0.

**Comment by vishal423** [comment]
Aside dependencies and docker images/keycloak realm, do you see any specific feature that would be helpful to wait for? 

I have few more Quarkus specific feature updates in mind and will create tickets for same (though not very sure if I can spend time on those :) )

**Comment by mraible** [comment]
@vishal423 No. Upgrading to JHipster 8 and Quarkus 3 is enough to warrant a release. I think that's a good foundation, and we can add new features in minor releases.

**Comment by anothergoodguy** [comment]
> Aside dependencies and docker images/keycloak realm, do you see any specific feature that would be helpful to wait for?
> 
> I have few more Quarkus specific feature updates in mind and will create tickets for same (though not very sure if I can spend time on those :) )
Please advise if you want me to file a separate feature request, but would like to request `hibernate search` integration with `jhipster-quarkus` blue print

**Comment by mshima** [comment]
> > Aside dependencies and docker images/keycloak realm, do you see any specific feature that would be helpful to wait for?
> > I have few more Quarkus specific feature updates in mind and will create tickets for same (though not very sure if I can spend time on those :) )
> 
> Please advise if you want me to file a separate feature request, but would like to request `hibernate search` integration with `jhipster-quarkus` blue print

I think you should open a new feature request.

**Comment by mshima** [comment]
I will start working on the v8 migration.

**Comment by mshima** [comment]
@mraible https://github.com/jhipster/generator-jhipster-quarkus/pull/301 cleanups CI post merging.
Is something else missing?

**Comment by mraible** [comment]
LGTM! What do you think @vishal423?

**Comment by vishal423** [comment]
Overall looks good to me. I am traveling and wouldn't be able to take
closer look before last week of November.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/187979.

**Comment by DanielFran** [comment]
@mshima approved
