### ISSUE TITLE
Service classes in wrong package

### ISSUE THREAD

**Issue by emilpaw** [jhipster/generator-jhipster-quarkus#312]
**Describe the bug**
While working on #311 I noticed that the service classes are placed in the wrong package. Instead of adding them to the `service` package, they are added to `service.impl`.

**To Reproduce**
Generate an application that uses service classes. It doesn't matter if the service classes are created because of the `dto` or `service` option. 
```
application {
  config {
    prodDatabaseType postgresql
  }

  entities *
}

entity Category {
  description String required
}
entity Post {
  title String required
}
service Category with serviceClass
dto Post with mapstruct
```

**Expected behavior**
The service classes are in the `service` package and not in `impl`. All the imports expect the service classes to be in `service`, and also the base JHipster generator does not use an `impl` package like that.

**Comment by mraible** [comment]
@emilpaw Can you please create a PR to fix this?
