### ISSUE TITLE
Dependabot auto-merge needs workflows status requirements

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster-quarkus#332]
**Describe the bug**
PRs with auto-merge without requirements will be merged as soon as the PR is created

**Comment by mraible** [comment]
I don't have access to set branch protection settings. @vishal423 Do you?

**Comment by vishal423** [comment]
looks like I do have access to configure that. Let me configure

**Comment by vishal423** [comment]
done. let me know if looks good

**Comment by mshima** [comment]
@vishal423 drop license requirement, dependabot PRs doesn’t meet it.

**Comment by vishal423** [comment]
I could see that's not an issue on svelte blueprint. Where did you encounter this issue?

**Comment by mshima** [comment]
I suppose dependabot was added to whitelist.
I thought I’ve seen the problem yesterday at react-native blueprint.
Looks good.
