### ISSUE TITLE
Release 3.1.0 with JHipster 8.2 support

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#344]
**Is your feature request related to a problem? Please describe.**

Please create a new release with JHipster 8.2 and Node 20 support.

**Describe the solution you'd like**

A new release.

**Comment by vishal423** [comment]
I will start release activities

**Comment by vishal423** [comment]
Published new version https://www.npmjs.com/package/generator-jhipster-quarkus/v/3.1.0
Updated sample application - https://github.com/jhipster/jhipster-sample-app-quarkus
Fixed Sonar cloud integration of sample application -- https://sonarcloud.io/project/overview?id=jhipster_jhipster-sample-app-quarkus

**Comment by vishal423** [comment]
@pascalgrimaud  bounty claimed https://opencollective.com/generator-jhipster/expenses/199459

**Comment by pascalgrimaud** [comment]
@vishal423 : approved
