### ISSUE TITLE
CLI accepts any value as authentication type

### ISSUE THREAD

**Issue by emilpaw** [jhipster/generator-jhipster-quarkus#352]
**Describe the bug**
The CLI asks for a text input for the authentication type and accepts any value. The generation succeeds, but the resulting application can't be compiled.

![Invalid input is accepted](https://github.com/jhipster/generator-jhipster-quarkus/assets/39118431/374bafc6-bebb-4b2e-90de-f128a8dc1d3d)

**Expected behavior**
Let the user select an authentication type like in the base generator:
![Authentication type selection](https://github.com/jhipster/generator-jhipster-quarkus/assets/39118431/734f8f98-75a4-4460-8e68-085537d56802)

**Comment by mraible** [comment]
Added a bug bounty to get this fixed.

**Comment by emilpaw** [comment]
@mraible
Cool, thanks! I'm working on it.
