### ISSUE TITLE
Dependabot doesn't work

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#356]
**Describe the bug**

If I look at the dependabot configuration for this project, it only lists Maven and Gradle rather than their paths. 

<img width="928" alt="Screenshot 2024-06-11 at 14 10 05" src="https://github.com/jhipster/generator-jhipster-quarkus/assets/17892/718b5428-2069-42bd-a2e2-cee01e6cb5fb">

It also can't seem to find the files in the specified directory.

<img width="922" alt="Screenshot 2024-06-11 at 14 10 25" src="https://github.com/jhipster/generator-jhipster-quarkus/assets/17892/ac42be23-a0d7-4b7e-84eb-23f8c9cb91fc">

**Comment by emilpaw** [comment]
I got some progress on this in my fork: https://github.com/emilpaw/generator-jhipster-quarkus/pull/2

**Comment by mshima** [comment]
I think that a gradle catalog is easier to maintain instead is a pom.xml.
https://github.com/jhipster/generator-jhipster/blob/main/generators/server/resources/gradle/libs.versions.toml

**Comment by emilpaw** [comment]
@mshima Not sure if I get your suggestion. Is there a way to use the Gradle catalog for both Maven and Gradle dependency versions? I supposed they must be handled each on their own, and I started with Maven because I am more familiar with it.

**Comment by mshima** [comment]
@emilpaw please continue witth pom.xml.
Gradle catalog have the entire dependency info in a single line while pom structure is more complex.
It’s just for information.
