### ISSUE TITLE
Missing imports when generating quarkus with mongodb

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster-quarkus#363]
**Describe the bug**

imports of @query, Page Pageable, @DBRef, @Field, List
are all missing in domain/*.java annotated with @mongoEntity

**To Reproduce**

jhipster-quarkus

**Expected behavior**
app is generated without any warnings but
java code does not compile

**Desktop (please complete the following information):**

-   OS: mac
-   node: 20.12.2
-   jhipster 8.2.1 (generation does not run successfully with generator-jhipster@6.5.20, so)
-   jhipster-quarkus 3.2.0

**Additional context**
native queries in form of spring jpa are currently not supported in quarkus

[Label.json](https://github.com/user-attachments/files/15954342/Label.json)
[.yo-rc.json](https://github.com/user-attachments/files/15954345/default.yo-rc.json)

**Comment by mraible** [comment]
Closing due to lack of response.
