### ISSUE TITLE
generated quarkus app always use h2 database on dev and prod

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster-quarkus#364]
**Describe the bug**

database properties in application.properties are not working

**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by mraible** [comment]
Can you please provide steps to reproduce this issue?

**Comment by mraible** [comment]
Closing due to lack of response.
