### ISSUE TITLE
Machine friendly exceptions

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster-quarkus#4]
JHipster Spring integrates Zalando problems (more precisely the spring version of the lib) to transform Java exception into machine readable exceptions (ie. HTTP status code + a JSON document).

Quarkus does not provide out of the box such feature. The objective is to emulate the same behavior (or simply try to integrate the vanilla Zalando problem lib) in order to be pluggable to the default front applications.

**Comment by joewhite101** [comment]
is this one the same as https://github.com/jhipster/jhipster-quarkus/issues/17

**Comment by danielpetisme** [comment]
@joewhite101 yes could be considered as duplicate.
The initial issue wasn't assuming any library choice but to be honest I don't know any good alternative to Zalando problems.
In other hands, I don't even know if it's feasible.

I'll close #17 and continue the discussion on this one.

**Comment by inngvar** [comment]
I can try to integrate it using https://github.com/cloudstark/quarkus-zalando-problem-extension extension.

**Comment by danielpetisme** [comment]
Definitively worth to try! Awesome if someone already made the integration.
 I don't see a lot of activity on the project, so if the experimentation is successful I propose we should contact the project authors.
The idea is to be sure we could get some help when people will generate JHipster projects with the zalando extension. Otherwise would make senses to re-implement it (and prevent a coupling on an inactive project).

**Comment by lwitkowski** [comment]
@danielpetisme I can give it a shot with [a new extension published recently](https://github.com/TietoEVRY/quarkus-resteasy-problem) I'm contributing to that fits this issue pretty well.

I've already had a quick look, and it would save me a lot of time to know if there will be some changes needed in the frontend as well? Can frontend app leverage problem schema to display better error messages etc?

**Comment by danielpetisme** [comment]
Hi,

The front end is already configured to handle problem payloads.
JHipster defines custom errors too that have to be translated into Quarkus Problems
https://github.com/jhipster/jhipster-sample-app/tree/main/src/main/java/io/github/jhipster/sample/web/rest/errors
The tricky part is this one
https://github.com/jhipster/jhipster-sample-app/blob/main/src/main/java/io/github/jhipster/sample/web/rest/errors/ExceptionTranslator.java

How can I help you to move forward?

**Comment by lwitkowski** [comment]
Thanks for hints, that sounds very good. `the tricky part` should just work, as ThrowableProblems are explicitly supported by our extension.
Could you also point me to specific action in UI I have to do (click) to see one of these exceptions returned from backend service and what should I see in the browser? I'll try to run sprinboot version later today to find out myself though :)

**Comment by danielpetisme** [comment]
🤔 
The basic errors are defined here:
https://github.com/jhipster/jhipster-sample-app/blob/main/src/main/java/io/github/jhipster/sample/web/rest/errors/ErrorConstants.java

To try to force an error, you can startup a generated app, log with the admin account (`admin`/`admin`), go to the Administration > User Management menu. Try to create a new user with an existing login for instance

**Comment by lwitkowski** [comment]
Thanks again, I see that quarkus generator uses raw `WebApplicationExceptions` or even `RuntimeException` here and there, which I'll probably have to convert into `ThrowableProblem`s to fully take advantage of `application/problem+json`, but that's fine, I'm on it.

**Comment by lwitkowski** [comment]
@danielpetisme you may want to have a first look at draft PR with first working implementation, I've checked both maven and gradle versions with multiple languages (but only selected subset of exceptions) - looks ok.

One thing that worries me a bit is that I didn't have to change a single test and all are green - do you think I should address it somehow and include some checks on response bodies (`application/problem+json`)?
