### ISSUE TITLE
Add Auth 2.0 / OIDC Support

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#47]
**Is your feature request related to a problem? Please describe.**

Please add OAuth 2.0 / OIDC support. This should be similar to our Spring Boot support in that it does login (on a monolith and gateway) and allows it to act as a resource server as well (for React Native and Ionic apps).

**Describe the solution you'd like**

I'd like to be able to choose OAuth 2.0 / OIDC for authentication, create some entities, start the app, and run `npm run e2e` to see all the tests pass. 

This is the JDL I used to test Micronaut:

```
application {
  config {
    baseName blog,
    applicationType monolith,
    packageName com.jhipster.demo.blog,
    prodDatabaseType mysql,
    authenticationType oauth2,
    cacheProvider hazelcast,
    buildTool maven,
    useSass true,
    testFrameworks [protractor]
  }
  entities *
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{entry}
}

paginate Post, Tag with infinite-scroll
```

**Comment by jdubois** [comment]
$500 bug bounty added, as discussed with @mraible 👍

**Comment by MR-Os1** [comment]
Hi
could you specify what features in the current version of the jhipster-quarkus is not working so i can have a list to work on ?

**Comment by mraible** [comment]
@MR-Os1 See the [open issues](https://github.com/jhipster/jhipster-quarkus/issues) in this project.

**Comment by mraible** [comment]
Any updates on this one @joewhite101?

**Comment by avdev4j** [comment]
closed by https://github.com/jhipster/generator-jhipster-quarkus/pull/124

don't forget to claim your bounty @danielpetisme

**Comment by pascalgrimaud** [comment]
bounty approved, good job @danielpetisme
