### ISSUE TITLE
Native testing support

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster-quarkus#49]
**Is your feature request related to a problem? Please describe.**
While generating a native executable, the generated project does not provide a support for native executable testing.

This absence of testing is based on 2 limitations:
- Failsafe `3.0.0-M4` does not detect the native test method ( as for now I don't know if it's due to Quarkus or failsafe)
- Native testing does not support `@Inject` and the whole test strategy relies on a liquibase injection reseting the test DB before each test.

**Describe the solution you'd like**
Native testing should focus on testing the executable only without coupling to the Databse thus no injection.

**Describe alternatives you've considered**
Manua testing

**Additional context**

**Comment by mraible** [comment]
@danielpetisme Can you please give me access to add labels to this project? That way I can add some bug bounties.
