### ISSUE TITLE
Application docker support

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster-quarkus#52]
**Is your feature request related to a problem? Please describe.**
The generator provide the standard Quarkus Dockerfile and also generate the classic JHipster docker files.

**Describe the solution you'd like**
The blueprint should merge and clean Docker files tailored for Quarkus.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by joewhite101** [comment]
@danielpetisme Did you have something specific in mind on this one? Looks like you did a lot of this one already. I'll update based on the newest Quarkus dockerfiles but it doesn't look like there are huge differnces.

**Comment by joewhite101** [comment]
Related https://github.com/jhipster/jhipster-quarkus/pull/88

**Comment by avdev4j** [comment]
closed by #88
