### ISSUE TITLE
No-SQL Support

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster-quarkus#7]
Quarkus proposes a MongoDB support.

The objective is to let the user choose MongoDB as data store and generate the according templates.

**Comment by amanganiello90** [comment]
I can start this task

**Comment by amanganiello90** [comment]
What is your advice? I read this guide: https://quarkus.io/guides/mongodb
What templates we have to add? Maybe a service and domain classes only? (it isn't as JPA with repository classes)

**Comment by danielpetisme** [comment]
The service layer shouldn't be impacted by the data persistent choice so we don't need to update it.
You should have a look to:
https://quarkus.io/guides/mongodb-panache
Quarkus proposes the repository pattern and active record. Since JHipster already relies on repository I think it's easier to stay on this pattern in a first version (even if it's not very Quarkus idiomatic)

So basically:
- Generate an Entity (I didn't test the following code...)
```
@MongoEntity(collection="ThePerson")
public class Person {

    public ObjectId id;
    public String name;
}
```
and a repostory
```
@ApplicationScoped
public class PersonRepository implements PanacheMongoRepository<Person> {

   public Person findByName(String name){
       return find("name", name).firstResult();
   }

}
```

**Comment by amanganiello90** [comment]
Perfect! Working with reactive nosql database, I thought to use client classes, so the pattern with repository and entity classes was not usefull. But If we want to keep jhipster design, as your advice I use the same standard patter with mongodb-panache. Thanks

**Comment by danielpetisme** [comment]
"Better done, than perfect" I focus on delievery a 0.0.1 this month so I focus on the big fishes.

**Comment by amanganiello90** [comment]
> 
> 
> "Better done, than perfect" I focus on delievery a 0.0.1 this month so I focus on the big fishes.

Right! it is the simple agile principle ;)... I did it also in my nodejs blueprint

**Comment by joewhite101** [comment]
Is this covered by this PR?

https://github.com/jhipster/jhipster-quarkus/pull/15

The status on the PR isn't totally clear.

**Comment by amanganiello90** [comment]
> 
> 
> Is this covered by this PR?
> 
> #15
> 
> The status on the PR isn't totally clear.

Hi, the PR is in progress and not completed (you can consider that declined)

**Comment by mraible** [comment]
@joewhite101 If you give me permissions to add labels to this repo, I can add a bug bounty to this issue.

**Comment by joewhite101** [comment]
@avdev4j I don't think I have enough access. Can you give @mraible the access needed to add labels?

**Comment by avdev4j** [comment]
I've just added @mraible as a maintainer of the project. Please Matt, tell me if is this is enough. Bug bounty labels are already created for this label.

**Comment by mraible** [comment]
That worked! Thanks, @avdev4j.
