### ISSUE TITLE
Roadmap to add Quarkus blueprint to official blueprints page on the website

### ISSUE THREAD

**Issue by joewhite101** [jhipster/generator-jhipster-quarkus#71]
**Is your feature request related to a problem? Please describe.**

It would be great to see the Quarkus blueprint on the Officially Supported Blueprints page: https://www.jhipster.tech/modules/official-blueprints/

Is there a feature set that is missing that we should add to the blueprint to get it added or is it just a matter of adding a PR to the github.io project?

**Describe the solution you'd like**
Make the required changes to get it posted

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by joewhite101** [comment]
cc @jdubois and @danielpetisme It would be good if we can add the blueprint since it is in the main github org. But if there is a feature gap then we can get tickets opened. 

If we can add it already let me know and i'll updated and create the .io project PR.

**Comment by danielpetisme** [comment]
IMHO, the project can be added right now with a "Work in progress, don't use it in prod"-like disclaimer.
@jdubois Make sense to you?

**Comment by jdubois** [comment]
Oh yes we should advertise it, but warn people it's not finished. BTW I tried it a couple of days ago, and the native prod build didn't include the front end... So indeed it's not ready for prod :-)

**Comment by joewhite101** [comment]
I'll open a ticket for the native FE build. Does the JVM build include the frontend and just the native build doesn't work? Or is the FE not bundled in both cases?

**Comment by joewhite101** [comment]
@jdubois Added a ticket for the native build issue. If you've got any additional info it is in https://github.com/jhipster/jhipster-quarkus/issues/78

Might be a good one for somebody at JHipster code.

**Comment by avdev4j** [comment]
closed by https://github.com/jhipster/jhipster.github.io/pull/1038
