### ISSUE TITLE
Regenerate and add sample project to CI

### ISSUE THREAD

**Issue by joewhite101** [jhipster/generator-jhipster-quarkus#74]
**Is your feature request related to a problem? Please describe.**
The sample project should be updated to a newer version and added to CI (see instructions here https://github.com/jhipster/jhipster-quarkus/issues/68)

**Describe the solution you'd like**
Project includes CI on commits and is integrated with Sonar

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by avdev4j** [comment]
Im sure to understand well this > he sample project should be added to CI

You mean into the CI generator you want to generate a sample project "on the fly" ?

**Comment by joewhite101** [comment]
No, we need to add a github action and workflow for the project so that the tests run when it changes. Already have the workflow file in a different ticket. I will attach it

**Comment by avdev4j** [comment]
Oh yes, I see.

**Comment by avdev4j** [comment]
The sample app have been updated https://github.com/jhipster/jhipster-sample-app-quarkus/pull/6
but the analysis can't be done. I think we just need to fix that and we will be able to close this ticket.

**Comment by avdev4j** [comment]
The sample project is now up to date. Every time is pushed on the main branche, the sonar analysis is triggered and the JHipster sonarCloud is updated.

https://sonarcloud.io/dashboard?id=jhipster_jhipster-sample-app-quarkus&branch=main&resolved=false
