### ISSUE TITLE
Creating a quarkus project without a client fails to start

### ISSUE THREAD

**Issue by joewhite101** [jhipster/generator-jhipster-quarkus#85]
**Describe the bug**
When creating a quarkus project without a client the maven project fails to start. The project should support generation without a client. 

**To Reproduce**

1. Run `jhipster --blueprints quarkus`
2. When prompted for `client` select `none'. 
3. Run `./mvnw`

Get error:

```
/opt/quarkusBpExample$ ./mvnw
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'build.plugins.plugin.version' for com.github.eirslett:frontend-maven-plugin must be a valid version but is '${frontend-maven-plugin.version}'. @ line 211, column 30
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.mycompany.myapp:quarkus-bp-example:1.0.0-SNAPSHOT (/opt/quarkusBpExample/pom.xml) has 1 error
[ERROR]     'build.plugins.plugin.version' for com.github.eirslett:frontend-maven-plugin must be a valid version but is '${frontend-maven-plugin.version}'. @ line 211, column 30
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

```
**Expected behavior**
Quarkus JHipster can generate without a client.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Running on master as of ticket opening

**Comment by joewhite101** [comment]
Should be just a matter of adding a skipClient check around this section of the pom

```
<plugin>
                    <groupId>com.github.eirslett</groupId>
                    <artifactId>frontend-maven-plugin</artifactId>
                    <version>${frontend-maven-plugin.version}</version>
                </plugin>
```

**Comment by SeaX** [comment]
Also around everything that is related to frontend :p 
maven plugins, webpack, statics, ....  I had a look in the following file: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/pom.xml.ejs

**Comment by joewhite101** [comment]
Yeah I've got a PR for this one that I need to finish:
https://github.com/jhipster/jhipster-quarkus/pull/87

Just a few small updates based on code review left.

**Comment by avdev4j** [comment]
done by #87
