### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster-quarkus#9]
JHipster Spring proposes to use a dedicated caching solution (hazelcast, ehcache, etc).
As for now, Quarkus only supports infinispan.

The objective is to permit the user to choose between the default Hibernate 2nd level caching or infinispan.

**Comment by avdev4j** [comment]
Great news !

We have a sample app with a Redis impl. Unfortunately I had to do all by myself, no abstraction is possible for the moment.

https://github.com/avdev4j/quarkus-redis-sample
