### ISSUE TITLE
Update repo name to follow the conventions

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster-quarkus#99]
**Describe the bug**
The GitHub repository should be generator-jhipster-quarkus instead of jhipster-quarkus.

**Additional context**
It could help the generator to be correctly indexed on npm repository and on JHipster website (all generators that stat by generator-jhipster-XXX).

**Comment by avdev4j** [comment]
I can do this one, WDYT @danielpetisme @joewhite101 ?

**Comment by danielpetisme** [comment]
Ok for me

**Comment by joewhite101** [comment]
Go for it.

**Comment by avdev4j** [comment]
I figured out that if we do this we will need to update our local repository to change the upstream to the new one. We don't have a lot of contributors for the moment so it will not be a big issue but we have to know that.

> git remote set-url upstream _new_url_

If you have a direct clone (not a fork one) of the repo the command should be 
> git remote set-url origin _new_url_

Is it still ok for you?

**Comment by joewhite101** [comment]
yeah. Now is the time.

**Comment by nshaw** [comment]
+1

**Comment by avdev4j** [comment]
Done, we can update our git config ;)

> git remote set-url upstream git@github.com:jhipster/generator-jhipster-quarkus.git
or if don't use SSH
> git remote set-url upstream https://github.com/jhipster/generator-jhipster-quarkus.git

I suggest to do the same with your fork (it seems to not be mandatory) and rename the origin: 

> git remote set-url origin git@github.com:<USERNAME>/generator-jhipster-quarkus.git
or if don't use SSH
> git remote set-url upstream https://github.com/<USERNAME>/generator-jhipster-quarkus.git
